constants:
  HUNDREDS_OF_SECONDS: 10000000
  EPOCH_AS_FILETIME: 116444736000000000
  HEADER_LIST:
    - Timestamp
    - Hostname
    - DiskNumber
    - Type
    - Offset
    - Size
    - ResponseTime
